_target_: pipeline.LabelInferPipeline
memory: ./cache/preprocessing/cat_boost
steps:
    - - CSVReader
      - _target_: pipeline.CSVReader
        _convert_: all
        file: data/accepted_2007_to_2018Q4.csv
        columns:
            - term
            - emp_length
            - home_ownership
            - verification_status
            - purpose
            - zip_code
            - addr_state
            - earliest_cr_line
            - application_type
            - verification_status_joint
            - sec_app_earliest_cr_line
            - disbursement_method
            - loan_amnt
            - fico_range_low
            - fico_range_high
            - revol_bal
            - emp_title
            - loan_status
    - - LabelTransformer
      - _target_: pipeline.LabelTransformer
        _convert_: all
    - - EmpTitle
      - _target_: pipeline.JobTransformer
        _convert_: all
        max_jobs: 20
    - - ImputeNumerical
      - _target_: pipeline.ApplyToColumns
        _convert_: all
        inner:
          _target_: sklearn.impute.SimpleImputer
          strategy: 'mean'
        columns:
          - loan_amnt
          - fico_range_low
          - fico_range_high
          - revol_bal
    - - ImputeCategorical
      - _target_: pipeline.ApplyToColumns
        _convert_: all
        inner:
          _target_: sklearn.impute.SimpleImputer
          strategy: 'most_frequent'
        columns:
          - term
          - emp_length
          - home_ownership
          - verification_status
          - purpose
          - zip_code
          - addr_state
          - earliest_cr_line
          - application_type
          - verification_status_joint
          - sec_app_earliest_cr_line
          - disbursement_method