_target_: pipeline.make_preprocessing_pipeline

steps_config:
    - CSVReader:
        _target_: pipeline.CSVReader
        _convert_: all
        file: data/accepted_2007_to_2018Q4.csv
        columns:
            - loan_amnt
            - term
            - int_rate
            - emp_title
            - emp_length
            - home_ownership
            - annual_inc
            - verification_status
            - loan_status
            - purpose
            - addr_state
            - dti
            - earliest_cr_line
            - fico_range_high
            - inq_last_6mths
            - revol_bal
            - initial_list_status
            - out_prncp
            - total_rec_late_fee
            - collection_recovery_fee
            - last_fico_range_low
            - collections_12_mths_ex_med
            - application_type
            - tot_coll_amt
            - avg_cur_bal
            - bc_open_to_buy
            - chargeoff_within_12_mths
            - delinq_amnt
            - mo_sin_old_il_acct
            - mo_sin_old_rev_tl_op
            - mo_sin_rcnt_tl
            - mort_acc
            - mths_since_recent_bc
            - num_accts_ever_120_pd
            - num_actv_bc_tl
            - num_bc_tl
            - num_il_tl
            - num_sats
            - num_tl_120dpd_2m
            - num_tl_30dpd
            - num_tl_90g_dpd_24m
            - num_tl_op_past_12m
            - pct_tl_nvr_dlq
            - percent_bc_gt_75
            - pub_rec_bankruptcies
            - tax_liens
            - total_il_high_credit_limit
            - disbursement_method
            - loan_status
            - funded_amnt
    - LabelTransformer:
        _target_: pipeline.LabelTransformer
        _convert_: all
    - ImputeNumerical:
        _target_: pipeline.ApplyToColumns
        _convert_: all
        inner:
            _target_: sklearn.impute.SimpleImputer
            strategy: 'mean'
        columns:
            - loan_amnt
            - int_rate
            - annual_inc
            - dti
            - fico_range_high
            - inq_last_6mths
            - revol_bal
            - out_prncp
            - total_rec_late_fee
            - collection_recovery_fee
            - last_fico_range_low
            - collections_12_mths_ex_med
            - tot_coll_amt
            - avg_cur_bal
            - bc_open_to_buy
            - chargeoff_within_12_mths
            - delinq_amnt
            - mo_sin_old_il_acct
            - mo_sin_old_rev_tl_op
            - mo_sin_rcnt_tl
            - mort_acc
            - mths_since_recent_bc
            - num_accts_ever_120_pd
            - num_actv_bc_tl
            - num_bc_tl
            - num_il_tl
            - num_sats
            - num_tl_120dpd_2m
            - num_tl_30dpd
            - num_tl_90g_dpd_24m
            - num_tl_op_past_12m
            - pct_tl_nvr_dlq
            - percent_bc_gt_75
            - pub_rec_bankruptcies
            - tax_liens
            - total_il_high_credit_limit
    - ImputeCategorical:
        _target_: pipeline.ApplyToColumns
        _convert_: all
        inner:
            _target_: sklearn.impute.SimpleImputer
            strategy: 'most_frequent'
        columns:
            - term
            - emp_title
            - emp_length
            - home_ownership
            - verification_status
            - purpose
            - addr_state
            - earliest_cr_line
            - initial_list_status
            - application_type
            - disbursement_method

