_target_: pipeline.LabelInferPipeline
memory: ./cache/preprocessing/log_reg
steps:
    - - CSVReader
      - _target_: pipeline.CSVReader
        _convert_: all
        file: data/accepted_2007_to_2018Q4.csv
        columns:
            - loan_amnt
            - term
            - emp_title
            - emp_length
            - home_ownership
            - verification_status
            - purpose
            - zip_code
            - addr_state
            - earliest_cr_line
            - fico_range_low
            - fico_range_high
            - revol_bal
            - application_type
            - verification_status_joint
            - sec_app_earliest_cr_line
            - loan_status
    - - LabelTransformer
      - _target_: pipeline.LabelTransformer
        _convert_: all
    - - ColumnTransformer
      - _target_: sklearn.compose.ColumnTransformer
        _convert_: all
        remainder: passthrough
        transformers:
            - - one_hot
              - _target_: sklearn.preprocessing.OneHotEncoder
              - - term
                - emp_length
                - home_ownership
                - verification_status
                - purpose
                - zip_code
                - addr_state
                - earliest_cr_line
                - application_type
                - verification_status_joint
                - sec_app_earliest_cr_line
                - disbursement_method
            - - scaler
              - _target_: sklearn.preprocessing.StandardScaler
              - - loan_amnt
                - fico_range_low
                - fico_range_high
                - revol_bal
            - - emp
              - _target_: pipeline.JobTransformer
                max_jobs: 20
              - - emp_title