_target_: pipeline.LabelInferPipeline
memory: ./cache/preprocessing/log_reg
steps:
    - - CSVReader
      - _target_: pipeline.CSVReader
        _convert_: all
        file: data/accepted_2007_to_2018Q4.csv
        columns:
            - funded_amnt
            - int_rate
            - emp_title
            - home_ownership
            - annual_inc
            - verification_status
            - purpose
            - dti
            - delinq_2yrs
            - fico_range_high
            - inq_last_6mths
            - pub_rec
            - revol_bal
            - out_prncp
            - total_rec_late_fee
            - recoveries
            - last_fico_range_low
            - collections_12_mths_ex_med
            - dti_joint
            - acc_now_delinq
            - tot_coll_amt
            - il_util
            - open_rv_24m
            - total_cu_tl
            - acc_open_past_24mths
            - chargeoff_within_12_mths
            - mo_sin_old_il_acct
            - mo_sin_old_rev_tl_op
            - mo_sin_rcnt_rev_tl_op
            - mths_since_recent_bc
            - mths_since_recent_revol_delinq
            - num_accts_ever_120_pd
            - num_actv_rev_tl
            - num_il_tl
            - num_tl_90g_dpd_24m
            - percent_bc_gt_75
            - tax_liens
            - sec_app_fico_range_low
            - sec_app_inq_last_6mths
            - sec_app_revol_util
            - sec_app_chargeoff_within_12_mths
            - sec_app_collections_12_mths_ex_med
            - sec_app_mths_since_last_major_derog
            - addr_state
            - load_status
    - - LabelTransformer
      - _target_: pipeline.LabelTransformer
        _convert_: all
    - - CustomTransformer
      - _target_: pipeline.CustomColumnTransformer
        _convert_: all
        us_urbanization_xlsx_path: docs/us_urbanization.xlsx
        fill_max_cols:
            - bc_open_to_buy
            - mths_since_last_delinq
            - mths_since_last_major_derog
            - mths_since_last_record
            - mths_since_rcnt_il
            - mths_since_recent_bc
            - mths_since_recent_bc_dlq
            - mths_since_recent_inq
            - mths_since_recent_revol_delinq
            - pct_tl_nvr_dlq
            - sec_app_mths_since_last_major_derog
        fill_mean_cols:
            - annual_inc
            - dti
            - sec_app_fico_range_low
            - sec_app_fico_range_high
            - total_rev_hi_lim
            - total_bc_limit
            - total_il_high_credit_limit
            - tot_hi_cred_lim
            - il_util
            - sec_app_revol_util
            - bc_util
    - - ColumnTransformer
      - _target_: sklearn.compose.ColumnTransformer
        _convert_: all
        remainder: passthrough
        transformers:
            - - one_hot
              - _target_: sklearn.preprocessing.OneHotEncoder
              - - emp_title
                - home_ownership
                - verification_status
                - purpose
            - - scaler
              - _target_: sklearn.preprocessing.StandardScaler
              - - bc_open_to_buy
                - mths_since_last_delinq
                - mths_since_last_major_derog
                - mths_since_last_record
                - mths_since_rcnt_il
                - mths_since_recent_bc
                - mths_since_recent_bc_dlq
                - mths_since_recent_inq
                - mths_since_recent_revol_delinq
                - pct_tl_nvr_dlq
                - sec_app_mths_since_last_major_derog
                - annual_inc
                - dti
                - sec_app_fico_range_low
                - sec_app_fico_range_high
                - total_rev_hi_lim
                - total_bc_limit
                - total_il_high_credit_limit
                - tot_hi_cred_lim
                - il_util
                - sec_app_revol_util
                - bc_util
