_target_: pipeline.make_pipeline

steps_config:
    - ColumnSelector:
        _target_: sklego.preprocessing.ColumnSelector
        columns:
            - loan_amnt
            - loan_status
            - term
            - int_rate
            - grade
            - sub_grade
            - emp_title
            - emp_length
            - home_ownership
            - annual_inc
            - verification_status
            - purpose
            - addr_state
            - dti
            - earliest_cr_line
            - fico_range_high
            - inq_last_6mths
            - revol_bal
            - initial_list_status
            - out_prncp
            - total_rec_late_fee
            - collection_recovery_fee
            - last_fico_range_low
            - collections_12_mths_ex_med
            - application_type
            - tot_coll_amt
            - avg_cur_bal
            - bc_open_to_buy
            - chargeoff_within_12_mths
            - delinq_amnt
            - mo_sin_old_il_acct
            - mo_sin_old_rev_tl_op
            - mo_sin_rcnt_tl
            - mort_acc
            - mths_since_recent_bc
            - num_accts_ever_120_pd
            - num_actv_bc_tl
            - num_bc_tl
            - num_il_tl
            - num_sats
            - num_tl_120dpd_2m
            - num_tl_30dpd
            - num_tl_90g_dpd_24m
            - num_tl_op_past_12m
            - pct_tl_nvr_dlq
            - percent_bc_gt_75
            - pub_rec_bankruptcies
            - tax_liens
            - total_il_high_credit_limit
            - disbursement_method
    - WingsOfEvidence:
        _target_: wing.WingsOfEvidence
        bin_minimal_size: 0.05
        bin_size_increase: 0.05
        is_monotone: false
        verbose: true
