_target_: pipeline.ReaderPipeline
memory: ./cache/preprocessing/raw
steps:
    - - CSVReader
      - _target_: pipeline.CSVReader
        _convert_: all
        file: data/accepted_2007_to_2018Q4.csv
        columns:
            - loan_amnt
            - term
            - emp_title
            - emp_length
            - home_ownership
            - verification_status
            - purpose
            - zip_code
            - addr_state
            - earliest_cr_line
            - fico_range_low
            - fico_range_high
            - revol_bal
            - application_type
            - verification_status_joint
            - sec_app_earliest_cr_line
            - loan_status
            - issue_d
            - funded_amnt
