_target_: sklearn.pipeline.Pipeline
memory: ./cache/classifier/cat_boost
steps:
    - - Classifier
      - _target_: catboost.CatBoostClassifier
        _convert_: all
        iterations: 500
        learning_rate: 0.01
        cat_features:
            - emp_title
            - home_ownership
            - verification_status
            - purpose
