_target_: sklearn.pipeline.Pipeline
memory: ./cache/classifier/cat_boost
steps:
    - - Classifier
      - _target_: catboost.CatBoostClassifier
        _convert_: all
        iterations: 500
        learning_rate: 0.01
        cat_features:
            - term
            - emp_length
            - home_ownership
            - verification_status
            - purpose
            - zip_code
            - addr_state
            - earliest_cr_line
            - application_type
            - verification_status_joint
            - sec_app_earliest_cr_line
            - disbursement_method
