_target_: pipeline.make_pipeline
name: classifier/log_reg

steps_config:
    - Classifier:
        _target_: sklearn.linear_model.LogisticRegression
        _convert_: all
        class_weight: balanced
