_target_: sklearn.pipeline.Pipeline
memory: ./cache/classifier/log_reg
steps:
    - - Classifier
      - _target_: sklearn.linear_model.LogisticRegression
        _convert_: all
        class_weight: balanced
