_target_: pipeline.make_classifier_pipeline

steps_config:
    - Classifier:
        _target_: pipeline.LogisticRegression
        max_epochs: 10
        lr: 0.01
        module__input_dim: 48
        module__output_dim: 1